open module com.mastfrog.async.promises {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.asyncpromises;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
