// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.async.promises {
    exports com.mastfrog.asyncpromises;

    // Inferred from test-source-scan
    requires transitive junit;

}
